apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: catnip-kearos-net
  namespace: cat
spec:
  secretName: cat-nip-tls
  dnsNames:
  - catnip.kearos.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - catnip.kearos.net
  issuerRef:
    name: cat-letsencrypt-staging
    kind: Issuer
