ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/issuer-kind: Issuer
    certmanager.k8s.io/issuer-name: cat-letsencrypt-staging 
  path: /
  hosts:
    - catnip.kearos.net
  tls: []
    - secretName: cat-nip-tls
      hosts:
        - catnip.kearos.net
